services:
  mysql:
    image: mysql:8.0
    container_name: mysql_xampp_like
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: Minhthuan
      MYSQL_PASSWORD: Minhthuan@123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: doangamifi
    environment:
      PMA_HOST: mysql
      PMA_USER: Minhthuan
      PMA_PASSWORD: Minhthuan@123
      PMA_ARBITRARY: "1"
    ports:
      - "8081:80"   # đổi sang 8085 nếu 8081 bận
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data:
